spring:
  application:
    name: database-sync-service-c
  
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 3s
        health-check-critical-timeout: 30s
        instance-id: ${spring.application.name}:${server.port}
        service-name: ${spring.application.name}
        tags:
          - microservice
          - database-sync
          - mongodb
          - version-1.0
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo-sync-c:27017/sync_db_c}
      database: ${SPRING_DATA_MONGODB_DATABASE:sync_db_c}
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:database-sync-service-c}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.example.sync.event"

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.sync: INFO
    org.springframework.cloud.consul: INFO
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: INFO 