spring:
  application:
    name: user-management-service
  
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: false  # Disable Consul for development
  
  datasource:
    url: jdbc:postgresql://localhost:5432/medihelp360
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
  
  # Disable Kafka for development
  kafka:
    enabled: false
  
  # Enable Flyway for development
  flyway:
    enabled: true
    baseline-on-migrate: true

# JWT Configuration
app:
  jwt:
    secret: dev-secret-key-for-testing-only
    expiration: 1800
    refresh-expiration: 604800

server:
  port: 8081
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.medihelp360.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
