spring:
  application:
    name: user-management-service
  
  # Disable all cloud features
  cloud:
    consul:
      enabled: false
    gateway:
      enabled: false
    loadbalancer:
      enabled: false
  
  # Simple H2 database
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Disable all external services
  kafka:
    enabled: false
  
  flyway:
    enabled: false
  
  # Disable security temporarily for testing
  security:
    enabled: false

# JWT Configuration
app:
  jwt:
    secret: test-secret-key
    expiration: 1800
    refresh-expiration: 604800

server:
  port: 8081
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.medihelp360.user: DEBUG
    org.springframework: DEBUG
